### ISSUE TITLE
Disable RF Support on GT Machines for GTCE

### ISSUE THREAD

**Issue by Hakameda** [GTNewHorizons/GTNewHorizons-3.0#6]
Keeping RF and EU seperate would be ideal similar to how it is now. It could also allow an RF type tier early on in the pack

**Comment by botn365** [comment]
why is there a GTCE ticket here?

**Comment by noobyaran9** [comment]
I don’t think GTCE have native rf support. And i don’t think gtce will be the gt of choice for gtnh 3 anyway.
Finally, has there been any development in gtnh 3 anyway?

**Comment by bartimaeusnek** [comment]
@Hakameda GTNH3 isnt updated and wont be updated soon.
